version: '3.8'
services:
  db:
    image: postgres:14.1
    container_name: testing_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testing_db
      - POSTGRES_USER=postgres
    ports:
      - 5433:5432